### ISSUE TITLE
vRealize: Push actions fails on Windows with build tools v2.30.0+

### ISSUE THREAD

**Issue by jskirde** [vmware/build-tools-for-vmware-aria#73] opened 2023-04-12 01:28 UTC
### Description
vRealize: Push actions fails on Windows with build tools v2.30.0+

### Steps to Reproduce

1. Setup project with POMs pointing to Aria Build Tools v2.30.0 or greater.
2. On a Windows machine, from Visual Studio Code, invoke the "vRealize: Push actions"
3. Error encountered

**Preconditions:**
- Pushing from Windows
- Aria build tools 2.30.0, 2.31.0 or 2.31.1
- Remove description tag from pom.xml (from the same level of groupid)

**Expected behavior:**
- Code should have been pushed

**Actual behavior:**
- Error message indicates `[ERROR] Missing groupId`

**Reproduces how often:**
- 100% reproducible on Windows. Does not happen on Linux.

**Component/s:**
- actions-package

**Affects Build/s:**
- 2.30.0
- 2.31.0
- 2.31.1

#### Client

-   Build Tools for VMware Aria Version: 2.31.1
-   Visual Studio Code Version: 1.65.2
-   OS Version: Windows Server 2016 - Version 1607 (OS Build 14393.5786)
-   Maven: 3.9.1
-   Node: 18.14.2

#### Server

-   vRealize Automation Version: 8.11.0.27829 (21128098)
-   vRealize Orchestrator Version: 8.11.0.27829 (21128098)
-   vRealize Operations Version: N/A
-   vRealize Log Insight Version: N/A

### Failure Logs
```
> Executing task: mvn clean package vrealize:push -DincludeDependencies=false -DskipTests -Pvra8-dev -pl actions <

[INFO] Scanning for projects...
Downloading from maven_mirror: https://artifactory.localdomin/artifactory/maven_mirror/com/vmware/pscoe/o11n/base-package/2.31.1/base-package-2.31.1.pom
Downloaded from maven_mirror: https://artifactory.localdomin/artifactory/maven_mirror/com/vmware/pscoe/o11n/base-package/2.31.1/base-package-2.31.1.pom (1.3 kB at 966 B/s)
Downloading from maven_mirror: https://artifactory.localdomin/artifactory/maven_mirror/com/vmware/pscoe/o11n/base-packages-parent/2.31.1/base-packages-parent-2.31.1.pom
Downloaded from maven_mirror: https://artifactory.localdomin/artifactory/maven_mirror/com/vmware/pscoe/o11n/base-packages-parent/2.31.1/base-packages-parent-2.31.1.pom (23 kB at 318 kB/s)
Downloading from maven_mirror: https://artifactory.localdomin/artifactory/maven_mirror/com/vmware/pscoe/iac/2.31.1/iac-2.31.1.pom
Downloaded from maven_mirror: https://artifactory.localdomin/artifactory/maven_mirror/com/vmware/pscoe/iac/2.31.1/iac-2.31.1.pom (7.0 kB at 115 kB/s)
Downloading from maven_mirror: https://artifactory.localdomin/artifactory/maven_mirror/com/vmware/pscoe/o11n/actions-package/2.31.1/actions-package-2.31.1.pom
Downloaded from maven_mirror: https://artifactory.localdomin/artifactory/maven_mirror/com/vmware/pscoe/o11n/actions-package/2.31.1/actions-package-2.31.1.pom
(5.2 kB at 56 kB/s)
Downloading from maven_mirror: https://artifactory.localdomin/artifactory/maven_mirror/com/vmware/pscoe/o11n/xml-package/2.31.1/xml-package-2.31.1.pom
Downloaded from maven_mirror: https://artifactory.localdomin/artifactory/maven_mirror/com/vmware/pscoe/o11n/xml-package/2.31.1/xml-package-2.31.1.pom (4.3 kB
at 158 kB/s)
Downloading from maven_mirror: https://artifactory.localdomin/artifactory/maven_mirror/com/vmware/pscoe/maven/plugins/o11n-actions-package-maven-plugin/2.31.1/o11n-actions-package-maven-plugin-2.31.1.pom
Downloaded from maven_mirror: https://artifactory.localdomin/artifactory/maven_mirror/com/vmware/pscoe/maven/plugins/o11n-actions-package-maven-plugin/2.31.1/o11n-actions-package-maven-plugin-2.31.1.pom (1.5 kB at 13 kB/s)
Downloading from maven_mirror: https://artifactory.localdomin/artifactory/maven_mirror/com/vmware/pscoe/maven/plugins/base-maven-plugin/2.31.1/base-maven-plugin-2.31.1.pom
Downloaded from maven_mirror: https://artifactory.localdomin/artifactory/maven_mirror/com/vmware/pscoe/maven/plugins/base-maven-plugin/2.31.1/base-maven-plugin-2.31.1.pom (5.2 kB at 88 kB/s)
Downloading from maven_mirror: https://artifactory.localdomin/artifactory/maven_mirror/com/vmware/pscoe/o11n/o11n-project/2.31.1/o11n-project-2.31.1.pom
Downloaded from maven_mirror: https://artifactory.localdomin/artifactory/maven_mirror/com/vmware/pscoe/o11n/o11n-project/2.31.1/o11n-project-2.31.1.pom (2.4 kB at 69 kB/s)
Downloading from maven_mirror: https://artifactory.localdomin/artifactory/maven_mirror/com/vmware/pscoe/iac/artifact-manager/2.31.1/artifact-manager-2.31.1.pom
Downloaded from maven_mirror: https://artifactory.localdomin/artifactory/maven_mirror/com/vmware/pscoe/iac/artifact-manager/2.31.1/artifact-manager-2.31.1.pom (4.9 kB at 8.0 kB/s)
Downloading from maven_mirror: https://artifactory.localdomin/artifactory/maven_mirror/net/minidev/json-smart/2.4.9/json-smart-2.4.9.pom
Downloaded from maven_mirror: https://artifactory.localdomin/artifactory/maven_mirror/net/minidev/json-smart/2.4.9/json-smart-2.4.9.pom (9.2 kB at 112 kB/s)
Downloading from maven_mirror: https://artifactory.localdomin/artifactory/maven_mirror/net/minidev/accessors-smart/2.4.9/accessors-smart-2.4.9.pom
Downloaded from maven_mirror: https://artifactory.localdomin/artifactory/maven_mirror/net/minidev/accessors-smart/2.4.9/accessors-smart-2.4.9.pom (11 kB at 58 kB/s)
Downloading from maven_mirror: https://artifactory.localdomin/artifactory/maven_mirror/org/ow2/asm/asm/9.3/asm-9.3.pom
Downloaded from maven_mirror: https://artifactory.localdomin/artifactory/maven_mirror/org/ow2/asm/asm/9.3/asm-9.3.pom (2.4 kB at 20 kB/s)
Downloading from maven_mirror: https://artifactory.localdomin/artifactory/maven_mirror/org/springframework/spring-core/5.2.23.RELEASE/spring-core-5.2.23.RELEASE.pom
Downloaded from maven_mirror: https://artifactory.localdomin/artifactory/maven_mirror/org/springframework/spring-core/5.2.23.RELEASE/spring-core-5.2.23.RELEASE.pom (1.7 kB at 8.3 kB/s)
Downloading from maven_mirror: https://artifactory.localdomin/artifactory/maven_mirror/org/springframework/spring-jcl/5.2.23.RELEASE/spring-jcl-5.2.23.RELEASE.pom
Downloaded from maven_mirror: https://artifactory.localdomin/artifactory/maven_mirror/org/springframework/spring-jcl/5.2.23.RELEASE/spring-jcl-5.2.23.RELEASE.pom (1.5 kB at 13 kB/s)
Downloading from maven_mirror: https://artifactory.localdomin/artifactory/maven_mirror/com/vmware/pscoe/maven/plugins/common/2.31.1/common-2.31.1.pom
Downloaded from maven_mirror: https://artifactory.localdomin/artifactory/maven_mirror/com/vmware/pscoe/maven/plugins/common/2.31.1/common-2.31.1.pom (2.0 kB at 13 kB/s)
Downloading from maven_mirror: https://artifactory.localdomin/artifactory/maven_mirror/com/vmware/pscoe/maven/plugins/o11n-actions-package-maven-plugin/2.31.1/o11n-actions-package-maven-plugin-2.31.1.jar
Downloaded from maven_mirror: https://artifactory.localdomin/artifactory/maven_mirror/com/vmware/pscoe/maven/plugins/o11n-actions-package-maven-plugin/2.31.1/o11n-actions-package-maven-plugin-2.31.1.jar (16 kB at 205 kB/s)
Downloading from maven_mirror: https://artifactory.localdomin/artifactory/maven_mirror/com/vmware/pscoe/o11n/o11n-project/2.31.1/o11n-project-2.31.1.jar
Downloading from maven_mirror: https://artifactory.localdomin/artifactory/maven_mirror/org/ow2/asm/asm/9.3/asm-9.3.jar
Downloading from maven_mirror: https://artifactory.localdomin/artifactory/maven_mirror/net/minidev/json-smart/2.4.9/json-smart-2.4.9.jar
Downloading from maven_mirror: https://artifactory.localdomin/artifactory/maven_mirror/net/minidev/accessors-smart/2.4.9/accessors-smart-2.4.9.jar
Downloaded from maven_mirror: https://artifactory.localdomin/artifactory/maven_mirror/net/minidev/json-smart/2.4.9/json-smart-2.4.9.jar (120 kB at 691 kB/s)
Downloading from maven_mirror: https://artifactory.localdomin/artifactory/maven_mirror/org/springframework/spring-core/5.2.23.RELEASE/spring-core-5.2.23.RELEASE.jar
Downloading from maven_mirror: https://artifactory.localdomin/artifactory/maven_mirror/com/vmware/pscoe/iac/artifact-manager/2.31.1/artifact-manager-2.31.1.jar
Downloaded from maven_mirror: https://artifactory.localdomin/artifactory/maven_mirror/net/minidev/accessors-smart/2.4.9/accessors-smart-2.4.9.jar (30 kB at 57 kB/s)
Downloading from maven_mirror: https://artifactory.localdomin/artifactory/maven_mirror/org/springframework/spring-jcl/5.2.23.RELEASE/spring-jcl-5.2.23.RELEASE.jar
Downloaded from maven_mirror: https://artifactory.localdomin/artifactory/maven_mirror/org/springframework/spring-jcl/5.2.23.RELEASE/spring-jcl-5.2.23.RELEASE.jar (24 kB at 29 kB/s)
Downloading from maven_mirror: https://artifactory.localdomin/artifactory/maven_mirror/com/vmware/pscoe/maven/plugins/common/2.31.1/common-2.31.1.jar
Downloaded from maven_mirror: https://artifactory.localdomin/artifactory/maven_mirror/com/vmware/pscoe/o11n/o11n-project/2.31.1/o11n-project-2.31.1.jar (21 kB at 26 kB/s)
Downloaded from maven_mirror: https://artifactory.localdomin/artifactory/maven_mirror/org/ow2/asm/asm/9.3/asm-9.3.jar (122 kB at 148 kB/s)
Downloaded from maven_mirror: https://artifactory.localdomin/artifactory/maven_mirror/com/vmware/pscoe/maven/plugins/common/2.31.1/common-2.31.1.jar (31 kB at 36 kB/s)
Downloaded from maven_mirror: https://artifactory.localdomin/artifactory/maven_mirror/com/vmware/pscoe/iac/artifact-manager/2.31.1/artifact-manager-2.31.1.jar (684 kB at 579 kB/s)
Downloaded from maven_mirror: https://artifactory.localdomin/artifactory/maven_mirror/org/springframework/spring-core/5.2.23.RELEASE/spring-core-5.2.23.RELEASE.jar (1.4 MB at 1.2 MB/s)
Downloading from maven_mirror: https://artifactory.localdomin/artifactory/maven_mirror/com/vmware/pscoe/maven/plugins/o11n-xml-package-maven-plugin/2.31.1/o11n-xml-package-maven-plugin-2.31.1.pom
Downloaded from maven_mirror: https://artifactory.localdomin/artifactory/maven_mirror/com/vmware/pscoe/maven/plugins/o11n-xml-package-maven-plugin/2.31.1/o11n-xml-package-maven-plugin-2.31.1.pom (1.7 kB at 8.9 kB/s)
Downloading from maven_mirror: https://artifactory.localdomin/artifactory/maven_mirror/com/vmware/pscoe/maven/plugins/o11n-typescript-package-maven-plugin/2.31.1/o11n-typescript-package-maven-plugin-2.31.1.pom
Downloaded from maven_mirror: https://artifactory.localdomin/artifactory/maven_mirror/com/vmware/pscoe/maven/plugins/o11n-typescript-package-maven-plugin/2.31.1/o11n-typescript-package-maven-plugin-2.31.1.pom (1.5 kB at 2.1 kB/s)
Downloading from maven_mirror: https://artifactory.localdomin/artifactory/maven_mirror/com/vmware/pscoe/maven/plugins/o11n-xml-package-maven-plugin/2.31.1/o11n-xml-package-maven-plugin-2.31.1.jar
Downloaded from maven_mirror: https://artifactory.localdomin/artifactory/maven_mirror/com/vmware/pscoe/maven/plugins/o11n-xml-package-maven-plugin/2.31.1/o11n-xml-package-maven-plugin-2.31.1.jar (13 kB at 316 kB/s)
Downloading from maven_mirror: https://artifactory.localdomin/artifactory/maven_mirror/com/vmware/pscoe/maven/plugins/o11n-typescript-package-maven-plugin/2.31.1/o11n-typescript-package-maven-plugin-2.31.1.jar
Downloaded from maven_mirror: https://artifactory.localdomin/artifactory/maven_mirror/com/vmware/pscoe/maven/plugins/o11n-typescript-package-maven-plugin/2.31.1/o11n-typescript-package-maven-plugin-2.31.1.jar (20 kB at 320 kB/s)
Downloading from maven_mirror: https://artifactory.localdomin/artifactory/maven_mirror/com/vmware/pscoe/maven/plugins/vrealize-package-maven-plugin/2.31.1/vrealize-package-maven-plugin-2.31.1.pom
Downloaded from maven_mirror: https://artifactory.localdomin/artifactory/maven_mirror/com/vmware/pscoe/maven/plugins/vrealize-package-maven-plugin/2.31.1/vrealize-package-maven-plugin-2.31.1.pom (1.7 kB at 17 kB/s)
Downloading from maven_mirror: https://artifactory.localdomin/artifactory/maven_mirror/com/vmware/pscoe/maven/plugins/vrealize-package-maven-plugin/2.31.1/vrealize-package-maven-plugin-2.31.1.jar
Downloaded from maven_mirror: https://artifactory.localdomin/artifactory/maven_mirror/com/vmware/pscoe/maven/plugins/vrealize-package-maven-plugin/2.31.1/vrealize-package-maven-plugin-2.31.1.jar (19 kB at 441 kB/s)
[INFO]
[INFO] ---------------< au.com.company.project:vRO8Automation.actions >----------------
[INFO] Building vRO8Automation.actions 1.0.119
[INFO]   from pom.xml
[INFO] ------------------------------[ package ]-------------------------------
Downloading from maven_mirror: https://artifactory.localdomin/artifactory/maven_mirror/com/vmware/pscoe/iac/vropkg/2.31.1/vropkg-2.31.1.pom
Downloaded from maven_mirror: https://artifactory.localdomin/artifactory/maven_mirror/com/vmware/pscoe/iac/vropkg/2.31.1/vropkg-2.31.1.pom (1.4 kB at 2.8 kB/s)
Downloading from maven_mirror: https://artifactory.localdomin/artifactory/maven_mirror/com/vmware/pscoe/npm/lib/2.31.1/lib-2.31.1.pom
Downloaded from maven_mirror: https://artifactory.localdomin/artifactory/maven_mirror/com/vmware/pscoe/npm/lib/2.31.1/lib-2.31.1.pom (6.3 kB at 50 kB/s)
Downloading from maven_mirror: https://artifactory.localdomin/artifactory/maven_mirror/com/vmware/pscoe/iac/vrotest/2.31.1/vrotest-2.31.1.pom
Downloaded from maven_mirror: https://artifactory.localdomin/artifactory/maven_mirror/com/vmware/pscoe/iac/vrotest/2.31.1/vrotest-2.31.1.pom (1.3 kB at 21 kB/s)
Downloading from maven_mirror: https://artifactory.localdomin/artifactory/maven_mirror/com/vmware/pscoe/iac/typescript/2.31.1/typescript-2.31.1.pom
Downloaded from maven_mirror: https://artifactory.localdomin/artifactory/maven_mirror/com/vmware/pscoe/iac/typescript/2.31.1/typescript-2.31.1.pom (4.3 kB at
84 kB/s)
Downloading from maven_mirror: https://artifactory.localdomin/artifactory/maven_mirror/com/vmware/pscoe/iac/vro-scripting-api/2.31.1/vro-scripting-api-2.31.1.pom
Downloaded from maven_mirror: https://artifactory.localdomin/artifactory/maven_mirror/com/vmware/pscoe/iac/vro-scripting-api/2.31.1/vro-scripting-api-2.31.1.pom (1.3 kB at 6.0 kB/s)
Downloading from maven_mirror: https://artifactory.localdomin/artifactory/maven_mirror/com/vmware/pscoe/iac/vropkg/2.31.1/vropkg-2.31.1.tgz
Downloaded from maven_mirror: https://artifactory.localdomin/artifactory/maven_mirror/com/vmware/pscoe/iac/vropkg/2.31.1/vropkg-2.31.1.tgz (4.0 MB at 2.5 MB/s)
Downloading from maven_mirror: https://artifactory.localdomin/artifactory/maven_mirror/com/vmware/pscoe/iac/vrotest/2.31.1/vrotest-2.31.1.tgz
Downloading from maven_mirror: https://artifactory.localdomin/artifactory/maven_mirror/com/vmware/pscoe/iac/vro-scripting-api/2.31.1/vro-scripting-api-2.31.1.tgz
Downloaded from maven_mirror: https://artifactory.localdomin/artifactory/maven_mirror/com/vmware/pscoe/iac/vro-scripting-api/2.31.1/vro-scripting-api-2.31.1.tgz (16 kB at 24 kB/s)
Downloaded from maven_mirror: https://artifactory.localdomin/artifactory/maven_mirror/com/vmware/pscoe/iac/vrotest/2.31.1/vrotest-2.31.1.tgz (3.4 MB at 3.0 MB/s)
[INFO]
[INFO] --- clean:3.2.0:clean (default-clean-1) @ vRO8Automation.actions ---
[INFO] Deleting C:\vro8automation\actions\target
[INFO]
[INFO] --- vro:2.31.1:clean (default-clean) @ vRO8Automation.actions ---
[INFO]
[INFO] --- clean:3.2.0:clean (default-clean) @ vRO8Automation.actions ---
[INFO]
[INFO] --- vro:2.31.1:install-node-deps (default-install-node-deps) @ vRO8Automation.actions ---
[INFO] Dependency installation started
[INFO] Dependency installation finished
[INFO]
[INFO] --- dependency:3.0.0:copy-dependencies (copy-vro-dependencies) @ vRO8Automation.actions ---
[INFO] Copying vROMocking-1.0.1.package to C:\vro8automation\actions\target\dependency\vro\au.com.company.project.vROMocking-1.0.1.package
[INFO]
[INFO] --- dependency:3.0.0:copy-dependencies (copy-vra-dependencies) @ vRO8Automation.actions ---
[INFO]
[INFO] --- dependency:3.0.0:copy-dependencies (copy-vcd-ng-dependencies) @ vRO8Automation.actions ---
[INFO]
[INFO] --- dependency:3.0.0:copy-dependencies (copy-vra-ng-dependencies) @ vRO8Automation.actions ---
[INFO]
[INFO] --- dependency:3.0.0:copy-dependencies (copy-vrops-dependencies) @ vRO8Automation.actions ---
[INFO]
[INFO] --- dependency:3.0.0:copy-dependencies (copy-vrli-dependencies) @ vRO8Automation.actions ---
[INFO]
[INFO] --- dependency:3.0.0:copy-dependencies (copy-bsc-dependencies) @ vRO8Automation.actions ---
[INFO]
[INFO] --- dependency:3.0.0:copy-dependencies (copy-cs-dependencies) @ vRO8Automation.actions ---
[INFO]
[INFO] --- dependency:3.0.0:copy-dependencies (copy-abx-dependencies) @ vRO8Automation.actions ---
[INFO]
[INFO] --- resources:3.3.1:resources (default-resources) @ vRO8Automation.actions ---
[WARNING] Using platform encoding (Cp1252 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] Copying 332 resources from src\main\resources to target\classes
[INFO]
[INFO] --- dependency:3.0.0:unpack (unpack-keystore) @ vRO8Automation.actions ---
[INFO] Configured Artifact: com.vmware.pscoe.build:archetype.keystore:3.0.0:zip
[WARNING] The POM for com.vmware.pscoe.build:archetype.keystore:zip:3.0.0 is missing, no dependency information available
[INFO] Unpacking C:\Users\thisuser\.m2\repository\com\vmware\pscoe\build\archetype.keystore\3.0.0\archetype.keystore-3.0.0.zip to C:\vro8automation\actions\target with includes "" and excludes ""
[INFO]
[INFO] --- vro:2.31.1:run-vro-tests (default-run-vro-tests) @ vRO8Automation.actions ---
[INFO] Tests are skipped.
[INFO]
[INFO] --- vro:2.31.1:package (default-package) @ vRO8Automation.actions ---
[INFO] Project basedir: C:\vro8automation\actions
[INFO] Package name 'au.com.company.project.vRO8Automation.actions-1.0.119
[INFO] Building vRO package 'au.com.company.project.vRO8Automation.actions-1.0.119.package' to: C:\vro8automation\actions\target
[INFO] Running vropkg... started
[INFO]
[INFO] C:\vro8automation\actions>node "C:\vro8automation\actions\node_modules\@vmware-pscoe\vropkg\bin\\..\dist\cli.js" --in js --srcPath C:\vro8automation\actions --out flat --destPath C:\vro8automation\actions\target\vropkg --privateKeyPEM target/archetype.keystore-3.0.0/private_key.pem --certificatesPEM target/archetype.keystore-3.0.0/cert.pem --keyPass hidden --version 1.0.119 --packaging package --artifactId vRO8Automation.actions --description "Build Tools for VMware Aria provides development and release management tools for implementing automation solutions
[ERROR] Missing groupId
[INFO] info: Parsing vro javascript project folder path "C:\vro8automation\actions"...
[INFO] info: Using certificate file target/archetype.keystore-3.0.0/private_key.pem
[INFO] info: Using certificate file target/archetype.keystore-3.0.0/cert.pem
[INFO] Running vropkg... finished
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  02:29 min
[INFO] Finished at: 2023-04-12T10:54:57+10:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.vmware.pscoe.maven.plugins:o11n-actions-package-maven-plugin:2.31.1:package (default-package) on project vRO8Automation.actions: Fail to move artefact from: C:\vro8automation\actions\target\vropkg\au.com.company.project.vRO8Automation.actions-1.0.119.package to: C:\vro8automation\actions\target\au.com.company.project.vRO8Automation.actions-1.0.119.package: C:\vro8automation\actions\target\vropkg\au.com.company.project.vRO8Automation.actions-1.0.119.package (The system cannot find the file specified) -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
The terminal process "C:\Program Files\Git\bin\bash.exe '--login', '-c', 'mvn clean package vrealize:push -DincludeDependencies=false -DskipTests -Pvra8-dev -pl actions'" terminated with exit code: 1.
```

### Related issues and PRs
N/A

### Additional Context
I suspect this issue is caused by invoking the vropkg.cmd file with a multi-line description. It looks like this truncated the command passed to vropkg and results in the missing groupId.

**Comment by Michaelpalacce** [comment] 2023-04-26 06:45
@jskirde This is an issue with a missing <description> in the pom.xml. I think you managed to find this out? 😄 

closing it for now

**Comment by jskirde** [comment] 2023-04-27 00:11
Please re-open. This needs to be fixed.

**Comment by ivo-kotev** [comment] 2023-05-02 07:03
@jskirde - actually the behavior that you explained is most probably caused by the default shell that is set in VS Code and the escaping / detecting the proper shell is something that vRDT ( the VS Code Plugin) is doing.
One suggestion - set your VS Code shell to git-bash - then most probably you will no longer have the above issue.

Anyway the problem is still valid and leaving this open until it's fixed in the  vrealize-developer-tools repo or this case is cloned there.

The VS Code plugin is hosted here: https://github.com/vmware/vrealize-developer-tools

**Comment by jskirde** [comment] 2023-05-02 07:50
This issue is present when using git-bash.
The problem appears to be the line breaks in the description of the "o11n-actions-package-maven-plugin" package are not handled by vropkg.cmd. Even when using git-bash, vropkg.cmd is still called.

**Comment by kjiju** [comment] 2023-06-03 06:08
> This issue is present when using git-bash. The problem appears to be the line breaks in the description of the "o11n-actions-package-maven-plugin" package are not handled by vropkg.cmd. Even when using git-bash, vropkg.cmd is still called.
Fixed this in AbstractVroPkgMojo.java

By applying following solution.
   ```
             String descStr = "";
		if (project.getDescription() != null) {
			descStr = project.getDescription();
		}
		this.description = descStr.replaceAll("\\R", " ");
```

**Closed** 2023-06-27 10:19 UTC
Labels: bug, windows
