### ISSUE TITLE
Executing a vRO action within vscode is not working

### ISSUE THREAD

**Issue by unbreakabl3** [vmware/build-tools-for-vmware-aria#83] opened 2023-04-20 14:03 UTC
### Description

When trying to run an action inside the vscode, I am getting the following error.

```
# Running getVmWithTag.js
# An error occurred: Could not import exec package into vRO: Command 'mvn dependency:copy -Dartifact=com.vmware.pscoe.o11n:exec::package -DoutputDirectory="/Users/user/Library/Application Support/Code/User/globalStorage/vmware-pscoe.vrealize-developer-tools" -Dmdep.stripVersion=true ' exited with code 1

```
### Steps to Reproduce

1. Select the action to run
2. Click in Run Action

**Expected behaviour:** [What you expect to happen]

The action will run locally

**Actual behaviour:** [What actually happens]

The error above

**Reproduces how often:** [What percentage of the time does it reproduce]

**Component/s:** [What are the Build Tools for VMware Aria components affected by the issue (e.g. "common/artifact-manager", "maven/plugins/vra-ng", "typescript/vrotest", etc)]

`com.vmware.pscoe.o11n:exec` package

#### Client

-   Build Tools for VMware Aria Version: 2.31.0
-   Visual Studio Code Version: 1.77.3
-   OS Version: MacOS 13.4
- vRealize Developer Tool: 2.4.0

#### Server

-   vRealize Orchestrator Version: 8.11.x

**Comment by Michaelpalacce** [comment] 2023-04-24 09:50
A short update on this. 

We used to have an exec module that we used to bundle and publish ( part of https://github.com/vmware/build-tools-for-vmware-aria/tree/main/packages ).

This was recently removed, we need to investigate why and return it.


FYI @n-vodenicharski

**Comment by Michaelpalacce** [comment] 2023-04-24 15:03
Internal link:

https://stash.pscoe.vmware.com/projects/IFV/repos/toolchain/browse/packages/exec

This is the package we need re-added

**Comment by kjiju** [comment] 2023-06-26 16:36
Same bug is reported in https://github.com/vmware/vrealize-developer-tools/issues/122

According to this bug, the VRealize Developer Tools should show a button called " RUN VRO Action"

**Comment by kjiju** [comment] 2023-06-27 09:31
I was able to run VRO actions by clicking on dropdown item with three dots in upper right corner of vscode.
This is first tested in 2.13.3 version of toolchain. The action in VRO was run successfully by initiating the call from VSCode.

**Comment by unbreakabl3** [comment] 2023-06-27 09:37
> I was able to run VRO actions by clicking on dropdown item with three dots in upper right corner of vscode.
> This is first tested in 2.13.3 version of toolchain. The action in VRO was run successfully by initiating the call from VSCode.

That’s what I have in the tree dots dropdown:

![image](https://github.com/vmware/build-tools-for-vmware-aria/assets/13556249/765a3ef6-064c-4d71-875c-0b22ad8b9cdd)

And that a vRO Action button:

![image](https://github.com/vmware/build-tools-for-vmware-aria/assets/13556249/b8af2c93-443c-48dc-8df4-e1a4faafd06c)

This one is not working and I am getting the error I was initially posted. The build tool I am running now is 2.33.0

**Comment by kjiju** [comment] 2023-06-27 09:40
Yes, I am trying to reproduce error in 2.31.0 and 2.33.0
2.13.3 was used to understand the success condition. Without knowing success condition, I cannot know failure condition.

**Comment by kjiju** [comment] 2023-06-27 11:01
Couldn't reproduce error with 2.33.0.
This could be due to the VRO already containing the exec package : com.vmware.pscoe.o11n.exec-2.26.4.package
Exported the package, deleting the package in VRO and retrying.
[com.vmware.pscoe.o11n.exec-2.26.4.zip](https://github.com/vmware/build-tools-for-vmware-aria/files/11881162/com.vmware.pscoe.o11n.exec-2.26.4.zip)

**Comment by unbreakabl3** [comment] 2023-06-27 11:04
I think Ivo mentioned that this package was removed for some reason in one of the earlier releases. The latest one doesn’t have it, if its install if from scratch.

**Comment by kjiju** [comment] 2023-06-27 11:09
Ok, with 2.33.0, and no exec package in VRO, I  clicked on "run VRO action".
The exec package is automatically imported into VRO and then the action is executed.
"Could not import exec package into vRO" didn't appear.
There may be something else existing in my vsCode. Need to find it and remove it.

**Comment by unbreakabl3** [comment] 2023-06-27 11:11
> Ok, with 2.33.0, and no exec package in VRO, I clicked on "run VRO action".
> The exec package is automatically imported into VRO and then the action is executed.
> "Could not import exec package into vRO" didn't appear.
> There may be something else existing in my vsCode. Need to find it and remove it.

Thanks. Waiting for your feedback.

**Comment by kjiju** [comment] 2023-06-27 11:50
To ensure, nothing is stored in my VSCode or machine, I uninstalled the "vrealize developer tools" extension, removed exec package from VRO and re-executed "run Vro action",   the "vrealize developer tools" downloaded exec package again and imported exec package into VRO and ran the action successfully.

Looks like nothing is cached in VScode. 
Next step, Will try the mvn code 
`mvn dependency:copy -Dartifact=com.vmware.pscoe.o11n:exec::package -DoutputDirectory="/Users/user/Library/Application Support/Code/User/globalStorage/vmware-pscoe.vrealize-developer-tools" -Dmdep.stripVersion=true `

**Comment by kjiju** [comment] 2023-06-27 11:56
Error received on above mvn command
[ERROR] Error resolving version for plugin '.vmware.pscoe.o11n:exec' from the repositories [local (C:\Users\kjiju\.m2\repository), central (https://artifactory.pscoe.vmware.com/artifactory/pscoe)]: Plugin not found in any plugin repository -> [Help 1]
org.apache.maven.plugin.version.PluginVersionResolutionException: Error resolving version for plugin '.vmware.pscoe.o11n:exec' from the repositories [local (C:\Users\kjiju\.m2\repository), central (https://artifactory.pscoe.vmware.com/artifactory/pscoe)]: Plugin not found in any plugin repository
    at org.apache.maven.plugin.version.internal.DefaultPluginVersionResolver.selectVersion (DefaultPluginVersionResolver.java:256)

**Comment by unbreakabl3** [comment] 2023-06-27 11:58
Yep. That’s what Ivo mentioned that it was removed for some reason.

**Comment by kjiju** [comment] 2023-06-27 12:20
Please note that it is looking for ".vmware.pscoe.o11n:exec".
not "com.vmware.pscoe.o11n:exec"

This could be a maven version issue. The maven I am using is 3.8.7
I assume the exec package may be removed from workspace after making it a maven dependency. Will confirm this

**Comment by kjiju** [comment] 2023-06-28 07:35
RunAction.ts of vRDT version 2.4.0 has    async prepare(context: vscode.ExtensionContext) {
        try {
            this.logger.info(`Checking if workflow with ID ${RUN_SCRIPT_WORKFLOW_ID} exists in target vRO`)
            await this.restClient.getWorkflow(RUN_SCRIPT_WORKFLOW_ID)
        } catch (e) {
            await vscode.window.withProgress(
                {
                    location: vscode.ProgressLocation.Window
                },
                progress => {
                    return new Promise<void>(async (resolve, reject) => {
                        try {
                            this.logger.debug(`Error: ${e.message}`)
                            progress.report({ message: "Downloading exec package" })
                            this.logger.info("Downloading package 'com.vmware.pscoe.o11n.exec'.")
                            const execPackage = await this.getExecPackage(context)
                            progress.report({ message: "Importing exec package in vRO" })
                            this.logger.info("Importing package 'com.vmware.pscoe.o11n.exec'.")
                            await this.restClient.importPackage(execPackage)
                            resolve()
                        } catch (e) {
                            const errorMessage = `Could not import exec package into vRO: ${e.message}`
                            reject(errorMessage)
                        }
                    })
                }
            )
        }
    }

   private async getExecPackage(context: vscode.ExtensionContext): Promise<string> {
        const storagePath = context.globalStoragePath
        if (!fs.existsSync(storagePath)) {
            fs.mkdirSync(storagePath)
        }

        await this.mavenProxy.copyDependency(
            "com.vmware.pscoe.o11n",
            "exec",
            this.environment.buildToolsVersion,
            "package",
            storagePath
        )
        return path.join(storagePath, "exec.package")
    }

**Comment by kjiju** [comment] 2023-06-28 07:40
Trying to figure out what does copyDependency of MavenCliProxy do
import { AutoWire, Logger, LogMessage, **MavenCliProxy**, PomFile, proc, sleep, VroRestClient } from "@vmware/vrdt-common"

**Comment by kjiju** [comment] 2023-06-28 07:49
`copyDependency(
        groupId: string,
        artifactId: string,
        version: string,
        packaging: string,
        destinationDir: string
    ): Promise<proc.CmdResult> {
        const command =
            `mvn dependency:copy ` +
            `-Dartifact=${groupId}:${artifactId}:${version}:${packaging} ` +
            `-DoutputDirectory="${destinationDir}" ` +
            `-Dmdep.stripVersion=true `

        return proc.exec(command, { cwd: destinationDir }, this.logger)
    }
`
`mvn dependency:copy -Dartifact=${groupId}:${artifactId}:${version}:${packaging} -DoutputDirectory="${destinationDir}" -Dmdep.stripVersion=true `
mvn dependency:copy -Dartifact=com.vmware.pscoe.o11n:exec::package -DoutputDirectory="/Users/user/Library/Application Support/Code/User/globalStorage/vmware-pscoe.vrealize-developer-tools" -Dmdep.stripVersion=true 

Need to figure out where the package com.vmware.pscoe.o11n:exec is copied from.

**Comment by kjiju** [comment] 2023-06-28 11:07
Confirming the following from Windows environment.
1. In windows the exec package is downloaded to C:\Users\<userid>\.m2\repository\com\vmware\pscoe\o11n\exec
2. With vRealize Developer tools (vRdt ) version 2.4.0 the maven local repository will contain a file named "exec-2.26.4.package" after the download.
3. Once download is complete the exec package is imported to VRO using rest client.
4. The exec package contains the "Run Script" workflow which is responsible for running the eval method.

This confirms that in windows environment exec package need not be included in the packages folder as seen in
https://github.com/vmware/build-tools-for-vmware-aria/tree/IAC-463-Improve-workstation-onboarding-docs/packages

Next, I will confirm the commit which made these changes.

**Comment by kjiju** [comment] 2023-06-28 12:27
Author				      Timestamp					  Commit #
nvodenicharski@vmware.com 2023-02-27 18:31:47 +0200   16ba7f2 all poms point to iac pom, all poms uses {revision} version
Nikolay Vodenicharski     2023-02-27 18:16:05 +0200   c287729 add threading to build.yml
<in commit # 16ba7f2 exec package is not there; in commit # c287729 exec package is present>

**Comment by kjiju** [comment] 2023-06-28 14:01
Please notice the exec package in remote maven repository

**Comment by Michaelpalacce** [comment] 2023-06-29 09:11
@kjiju https://artifactory.pscoe.vmware.com/artifactory/pscoe/com/vmware/pscoe/o11n/exec/ is not remote, it's local to us, remote is maven central

**Comment by kjiju** [comment] 2023-06-29 12:46
I am able to reproduce the bug by adding two items in precondition
# Running actionSample.js
# An error occurred: Could not import exec package into vRO: Command 'mvn dependency:copy -Dartifact=com.vmware.pscoe.o11n:exec:2.26.4:package -DoutputDirectory="c:\Users\kjiju\AppData\Roaming\Code\User\globalStorage\vmware-pscoe.vrealize-developer-tools" -Dmdep.stripVersion=true ' exited with code 1

**### Preconditions:**
Remove m2/repository
Remove artifactory from settings.xml

**Comment by kjiju** [comment] 2023-06-30 10:41
2.29.2 is the version of vRbt having exec package.
By using this version as well as by adding exec folder to existing source code, I am getting following error

```
# Running getFileName.js
# An error occurred: Could not import exec package into vRO: Command 'mvn dependency:copy -Dartifact=com.vmware.pscoe.o11n:exec:2.26.4:package -DoutputDirectory="c:\Users\kjiju\AppData\Roaming\Code\User\globalStorage\vmware-pscoe.vrealize-developer-tools" -Dmdep.stripVersion=true ' exited with code 1
```

**Comment by unbreakabl3** [comment] 2023-12-04 14:07
Hey, everyone.
Is there any progress here? 
There is nothing here as well: https://github.com/vmware/vrealize-developer-tools/issues/122

**Comment by unbreakabl3** [comment] 2023-12-18 13:16
> @Michaelpalacce @kjiju @akumanov-vmw I think this issue is fixed with the following PR: [vmware/vrealize-developer-tools#140](https://github.com/vmware/vrealize-developer-tools/pull/140) @akumanov-vmw could you confirm if I am right? If that is the case, we should have the fix in the next release of vRDT

Amazing news. Like a gift for a Christmas 🤶. Thanks a lot! Will wait for a next release to test it.

**Comment by VenelinBakalov** [comment] 2023-12-19 08:43
Hi again @unbreakabl3 , I did some local tests with the latest code base. It seems to work, at least on my side. I would suggest, if you have time, to try and checkout the latest vRealize Developer Tools master, build it locally and test on your side to make sure it is functional for you as well.
I am leaving a screenshot with my test action and output:
![image](https://github.com/vmware/build-tools-for-vmware-aria/assets/22296648/7ea96479-1858-4909-8ca2-d78982c14d47)
![image](https://github.com/vmware/build-tools-for-vmware-aria/assets/22296648/741ed918-ca2a-4ab2-929b-cc9a2a029305)

**Comment by unbreakabl3** [comment] 2023-12-20 08:35
> Hi again @unbreakabl3 , I did some local tests with the latest code base. It seems to work, at least on my side. I would suggest, if you have time, to try and checkout the latest vRealize Developer Tools master, build it locally and test on your side to make sure it is functional for you as well. I am leaving a screenshot with my test action and output: ![image](https://private-user-images.githubusercontent.com/22296648/291527831-7ea96479-1858-4909-8ca2-d78982c14d47.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMwNjE1MzgsIm5iZiI6MTcwMzA2MTIzOCwicGF0aCI6Ii8yMjI5NjY0OC8yOTE1Mjc4MzEtN2VhOTY0NzktMTg1OC00OTA5LThjYTItZDc4OTgyYzE0ZDQ3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIwVDA4MzM1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ2NmQyZTc0NDNiNTY1ZGUxNDJlMmE2N2EwMzBhZWQyZDQ0NDQ0N2E2MWUzZjc5NGM1OGU2YWFiMmMzYmUwOTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jebCaXFXcQEWbJ6LFvkggayJLcjQo1PN1Kp89FIAs_Q) ![image](https://private-user-images.githubusercontent.com/22296648/291527867-741ed918-ca2a-4ab2-929b-cc9a2a029305.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMwNjE1MzgsIm5iZiI6MTcwMzA2MTIzOCwicGF0aCI6Ii8yMjI5NjY0OC8yOTE1Mjc4NjctNzQxZWQ5MTgtY2EyYS00YWIyLTkyOWItY2M5YTJhMDI5MzA1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIwVDA4MzM1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc2OGRjMGFkOGU4YjcwMjQ1Y2U1NTdhZDY0NGUxNzQxNWQ4ZjQ1ODc4NzlhYjI4OWQ2ZDMwNTY0NmUzOTZlZTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Ksd_BG6qNh_dFiuQwTGuwmlqzTFgBpMzpYsh1OWEoJY)

Hi, @VenelinBakalov. Working for me. 
Thank you very much.

**Comment by VenelinBakalov** [comment] 2023-12-20 08:42
That's great to hear! Let me try to organise a release and once it is done, I will write back here and close the related issues.

**Comment by VenelinBakalov** [comment] 2023-12-20 11:42
Hi again, @unbreakabl3 , thanks for the feedback and the patience!
Release 2.5.1 is available on the marketplace now: https://marketplace.visualstudio.com/manage/publishers/vmware-pscoe (and on github https://github.com/vmware/vrealize-developer-tools/releases/tag/v2.5.1)
I updated my local extension in VScode and it seems to be executing the action successfully. It would be great if you can also validate on your side with the latest release.

**Comment by VenelinBakalov** [comment] 2023-12-21 15:05
We did another internal validation round, everything should be ok, if you manage to find an issue feel free to reopen this thread.
Happy holidays and have a nice time off! :)

**Comment by VenelinBakalov** [comment] 2023-12-21 15:06
Issue closed in vRDT repository with PR: https://github.com/vmware/vrealize-developer-tools/pull/140
vRDT release v2.5.1 is addressing it

**Comment by simplygeekuk** [comment] 2024-01-19 11:19
@VenelinBakalov I just tried this and getting the same issue that 'com.vmware.pscoe.o11n:exec:2.36.0:package' cannot be found. I have a completely new install, using Build Tools v2.36.0 and vRDT 2.5.1. I have tried removing the extension and re-installing but keep getting the same problem.

**Comment by VenelinBakalov** [comment] 2024-01-26 12:36
Hi @simplygeekuk , this seems like a different error, could you add the full error log here and any configuration that you might see usefull?
It sounds a bit like mvn not being able to access Maven central to download the artifact but you mentioned you reinstalled the plugin from which I assume you have internet connectivity during the execution?

**Comment by unbreakabl3** [comment] 2024-01-26 13:36
Actually, I have the same problem now. Latest vscode, Build Tools v2.37.0 and vRDT 2.5.1:

```
An error occurred: Could not import exec package into vRO: Command 'mvn dependency:copy -Dartifact=com.vmware.pscoe.o11n:exec::package -DoutputDirectory="/Users/user/Library/Application Support/Code/User/globalStorage/vmware-pscoe.vrealize-developer-tools" -Dmdep.stripVersion=true ' exited with code 1
```

**Comment by simplygeekuk** [comment] 2024-01-26 13:37
@VenelinBakalov Looking at the conversation thread here, it's identified as the exec package being the problem (not able to download it). This package does not exist in the public Maven central repos, this is the problem.

**Comment by Michaelpalacce** [comment] 2024-01-26 21:24
I think we need to re-open this. We need to publish the exec plugin

**Comment by VenelinBakalov** [comment] 2024-01-28 20:21
Interesting, @unbreakabl3 what version where you using when the test was working for you?

**Comment by VenelinBakalov** [comment] 2024-01-28 20:25
@Michaelpalacce it seems the exec package was removed between 2.92.2 and 2.30.0 releases. probably this appeared as an issue now since we have created a new vRDT release
https://github.com/vmware/build-tools-for-vmware-aria/tree/v2.29.2/packages

**Comment by vsuddya** [comment] 2024-02-02 14:51
![run action](https://github.com/vmware/build-tools-for-vmware-aria/assets/127217826/c43b8a62-82b2-453d-8777-c86b62a54657)
For me it's working well. 
Build Tools v2.36.0 
vRDT 2.5.1
Visual Studio Code Version: 1.86.0 
Apache Maven 3.9.6
java 17.0.9

Looks like there is a version compatibility issue

**Comment by Michaelpalacce** [comment] 2024-02-02 15:05
Closing as per @vsuddya's investigations

**Closed by Michaelpalacce** 2024-02-02 15:05 UTC
Labels: bug, java, missing-dependencies, vrdt

**Comment by VenelinBakalov** [comment] 2024-02-12 08:51
@Michaelpalacce I think we might still need to add back the exec package to Build Tools repo

**Comment by unbreakabl3** [comment] 2024-02-12 15:05
> @Michaelpalacce I think we might still need to add back the exec package to Build Tools repo

I don't know the original reason for removing it, but if possible, it would be very useful to return it.
